version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: |
          curl --connect-timeout 120 https://hkjlkl54-farhahmarbawi.b4a.run/
          
workflows:
   nightly:
     jobs:
       - build
